Public Class RecTaskCommandData
    '    "TaskStarted",
    '"TaskEnded",
    '"Response",
    '"Event",
    '"RegisterClient",
    '"UnregisterClient",
    Public _rectaskcommand() As String = New String() {
"Hello",
"EndTask",
"LoadBonDriver",
"UnloadBonDriver",
"GetBonDriver",
"OpenTuner",
"CloseTuner",
"SetChannel",
"GetChannel",
"SetService",
"GetService",
"GetServiceList",
"OpenCasCard",
"CloseCasCard",
"GetStreamStatistics",
"ResetErrorStatistics",
"StartRecording",
"StopRecording",
"ChangeRecordingFile",
"GetRecordingInfo",
"GetEventInfo",
"GetLog",
"GetChannelList",
"GetBonDriverChannelList",
"GetScannedChannelList",
"CreateStreamPool",
"CloseStreamPool",
"GetTvRockInfo",
"StartStreaming",
"StopStreaming",
"GetStreamingInfo",
"GetSetting"
}

    Dim _rectaskproperty() As String = New String() {
"Result",
"Message",
"ErrorCode",
"TaskID",
"FilePath",
"Directory",
"FileName",
"TuningSpace",
"Channel",
"ChannelName",
"TuningSpaceName",
"NetworkID",
"TransportStreamID",
"ServiceName",
"ServiceID",
"ServiceType",
"ScannedChannel",
"ScannedServiceID",
"RemoteControlKeyID",
"Name",
"Value",
"Status",
"ServiceSelect",
"Descramble",
"Streams",
"StartTime",
"StartTickCount"
}

End Class
